name: bitconvert
description: Get bitcoins conversion rates.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  provider: ^6.0.3
  flutter_spinkit: ^5.1.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: KdamThmorPro
      fonts:
        - asset: fonts/KdamThmorPro-Regular.ttf
          weight: 400
    - family: Monserrat
      fonts:
        - asset: fonts/Montserrat-VariableFont_wght.ttf
          weight: 400

